-- Alertes doublons clients (UDF STDCIF) : pièce, NIF, adresse/tél/noms représentant légal
-- Aucun bind : liste globale pour le menu « Alertes doublons »
WITH udf_client_dc AS (
    SELECT
        sc.CUSTOMER_NO AS MATRICULE_CLIENT,
        sc.CUSTOMER_NAME1 AS RAISON_SOCIALE,
        b.BRANCH_CODE AS CODE_BUREAU,

        udf.FIELD_VAL_1 AS TITRE_REP_LEGAL,
        udf.FIELD_VAL_3 AS ADRESSE_REP_LEGAL,
        udf.FIELD_VAL_4 AS SEX_REP_LEGAL,
        lov_sexe.LOV_DESC AS GENRE_REP_LEGAL,

        udf.FIELD_VAL_5 AS TELEPHONE_REP_LEGAL,

        udf.FIELD_VAL_6 AS CODE_CONSENTEMENT_BIC,
        lov_consent.LOV_DESC AS CONSENTEMENT_BIC,

        udf.FIELD_VAL_7 AS NUMERO_BIC,

        udf.FIELD_VAL_8 AS CODE_NOM_PERE_REP_LEGAL,
        udf.FIELD_VAL_9 AS CODE_NOM_MERE_REP_LEGAL,

        udf.FIELD_VAL_10 AS COD_NAT_JURID,
        lov_nat.LOV_DESC AS LIB_NAT_JURID,

        udf.FIELD_VAL_12 AS COD_SOUS_SECTEUR_ACTIVITE,
        lov_ssecteur.LOV_DESC AS SOUS_SECTEUR,

        udf.FIELD_VAL_11 AS COD_SECTEUR_ACTIVITE,
        lov_secteur.LOV_DESC AS SECTEUR_ACTIVITE,

        udf.FIELD_VAL_13 AS CODE_GESTIONNAIRE_CLIENT,
        lov_gest.LOV_DESC AS GESTIONNAIRE_CLIENT,

        udf.FIELD_VAL_14 AS CODE_GESTIONNAIRE_CLIENT_INIT,
        lov_gest_init.LOV_DESC AS GESTIONNAIRE_CLIENT_INIT,

        udf.FIELD_VAL_15 AS CODE_APPORTEUR_AFFAIRE,
        lov_app.LOV_DESC AS NOM_APPORTEUR_AFFAIRE,

        udf.FIELD_VAL_16 AS DATE_EMISSION_PIECE,
        udf.FIELD_VAL_17 AS DATE_EXPIRATION_PIECE,
        udf.FIELD_VAL_18 AS TYPE_PIECE,
        udf.FIELD_VAL_19 AS NUMERO_DE_PIECE,

        udf.FIELD_VAL_20 AS NOM_MERE,
        udf.FIELD_VAL_21 AS LIEU_DE_NAISSANCE,
        udf.FIELD_VAL_22 AS DATE_DE_NAISSANCE,
        udf.FIELD_VAL_23 AS PAYS_DE_NAISSANCE,
        udf.FIELD_VAL_24 AS NATIONALITE,
        udf.FIELD_VAL_25 AS ADRESSE,

        udf.FIELD_VAL_26 AS RAISON_SOCIALE_UDF,
        udf.FIELD_VAL_27 AS DATE_CREATION_PERS_MORALE,
        udf.FIELD_VAL_28 AS NUMERO_IDENTIFICATION_FISCAL,
        udf.FIELD_VAL_29 AS REVENUS,

        udf.FIELD_VAL_30 AS LIEU_NAISSANCE_REP_LEGAL,
        udf.FIELD_VAL_31 AS PAYS_NAISSANCE_REP_LEGAL,
        udf.FIELD_VAL_32 AS DATE_NAISSANCE_REP_LEGAL,
        udf.FIELD_VAL_33 AS DATE_EMISSION_CNI,
        udf.FIELD_VAL_34 AS DATE_EXPIRATION_CNI,
        udf.FIELD_VAL_35 AS NUMERO_DE_PIECE_2

    FROM CFSFCUBS145.STTM_CUSTOMER sc

    LEFT JOIN CFSFCUBS145.CSTM_FUNCTION_USERDEF_FIELDS udf
        ON sc.CUSTOMER_NO = REPLACE(udf.REC_KEY, '~', '')
        AND udf.FUNCTION_ID = 'STDCIF'

    LEFT JOIN CFSFCUBS145.STTM_BRANCH b
        ON b.BRANCH_CODE = sc.LOCAL_BRANCH

    LEFT JOIN CFSFCUBS145.STTM_CUST_PERSONAL p
        ON sc.CUSTOMER_NO = p.CUSTOMER_NO

    LEFT JOIN CFSFCUBS145.STTM_CUST_CORPORATE c
        ON sc.CUSTOMER_NO = c.CUSTOMER_NO

    LEFT JOIN CFSFCUBS145.STTM_CUSTOMER_CAT cat
        ON cat.CUST_CAT = sc.CUSTOMER_CATEGORY

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_sexe
        ON lov_sexe.FIELD_NAME = 'SEXE_REP_LEGAL'
        AND lov_sexe.LOV = udf.FIELD_VAL_4

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_consent
        ON lov_consent.FIELD_NAME = 'CONSENTEMENT_BIC'
        AND lov_consent.LOV = udf.FIELD_VAL_6

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_nat
        ON lov_nat.FIELD_NAME = 'NAT_JURID'
        AND lov_nat.LOV = udf.FIELD_VAL_10

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_ssecteur
        ON lov_ssecteur.FIELD_NAME = 'CODE_SSECTEUR'
        AND lov_ssecteur.LOV = udf.FIELD_VAL_12

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_secteur
        ON lov_secteur.FIELD_NAME = 'SECTEUR_ACTIVITE'
        AND lov_secteur.LOV = udf.FIELD_VAL_11

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_gest
        ON lov_gest.FIELD_NAME = 'GEST_CLIENT'
        AND lov_gest.LOV = udf.FIELD_VAL_13

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_gest_init
        ON lov_gest_init.FIELD_NAME = 'GEST_CLIENT_INIT'
        AND lov_gest_init.LOV = udf.FIELD_VAL_14

    LEFT JOIN CFSFCUBS145.UDTM_LOV lov_app
        ON lov_app.FIELD_NAME = 'APP_AFFAIRE'
        AND lov_app.LOV = udf.FIELD_VAL_15

    WHERE sc.CUSTOMER_NO NOT LIKE '000001'
),
ALERTES AS (
    SELECT
        c1.MATRICULE_CLIENT,
        'MEME NUMERO_DE_PIECE_2' AS TYPE_LIEN,
        c2.MATRICULE_CLIENT AS PERSONNE_SOCIETE_LIEE,
        c1.RAISON_SOCIALE AS CLIENT,
        c2.RAISON_SOCIALE AS RAISON_SOCIALE_LIEE,
        c1.NUMERO_DE_PIECE_2 AS VALEUR_COMMUNE,
        'ELEVE' AS NIVEAU_RISQUE,
        'A_ANALYSER' AS STATUT,
        1 AS ORDRE_RISQUE
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON c1.NUMERO_DE_PIECE_2 = c2.NUMERO_DE_PIECE_2
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.NUMERO_DE_PIECE_2) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME NUMERO_IDENTIFICATION_FISCAL',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.NUMERO_IDENTIFICATION_FISCAL,
        'ELEVE',
        'A_ANALYSER',
        1
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON c1.NUMERO_IDENTIFICATION_FISCAL = c2.NUMERO_IDENTIFICATION_FISCAL
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.NUMERO_IDENTIFICATION_FISCAL) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME NUMERO_DE_PIECE',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.NUMERO_DE_PIECE,
        'ELEVE',
        'A_ANALYSER',
        1
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON UPPER(TRIM(c1.NUMERO_DE_PIECE)) = UPPER(TRIM(c2.NUMERO_DE_PIECE))
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.NUMERO_DE_PIECE) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME ADRESSE_REP_LEGAL',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.ADRESSE_REP_LEGAL,
        'MOYEN',
        'A_ANALYSER',
        2
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON UPPER(TRIM(c1.ADRESSE_REP_LEGAL)) = UPPER(TRIM(c2.ADRESSE_REP_LEGAL))
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.ADRESSE_REP_LEGAL) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME TELEPHONE_REP_LEGAL',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.TELEPHONE_REP_LEGAL,
        'MOYEN',
        'A_ANALYSER',
        2
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON REGEXP_REPLACE(c1.TELEPHONE_REP_LEGAL, '[^0-9]', '') =
           REGEXP_REPLACE(c2.TELEPHONE_REP_LEGAL, '[^0-9]', '')
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.TELEPHONE_REP_LEGAL) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME CODE_NOM_PERE_REP_LEGAL',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.CODE_NOM_PERE_REP_LEGAL,
        'MOYEN',
        'A_ANALYSER',
        2
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON UPPER(TRIM(c1.CODE_NOM_PERE_REP_LEGAL)) =
           UPPER(TRIM(c2.CODE_NOM_PERE_REP_LEGAL))
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.CODE_NOM_PERE_REP_LEGAL) IS NOT NULL

    UNION ALL

    SELECT
        c1.MATRICULE_CLIENT,
        'MEME CODE_NOM_MERE_REP_LEGAL',
        c2.MATRICULE_CLIENT,
        c1.RAISON_SOCIALE,
        c2.RAISON_SOCIALE,
        c1.CODE_NOM_MERE_REP_LEGAL,
        'MOYEN',
        'A_ANALYSER',
        2
    FROM udf_client_dc c1
    INNER JOIN udf_client_dc c2
        ON UPPER(TRIM(c1.CODE_NOM_MERE_REP_LEGAL)) =
           UPPER(TRIM(c2.CODE_NOM_MERE_REP_LEGAL))
        AND c1.MATRICULE_CLIENT <> c2.MATRICULE_CLIENT
    WHERE TRIM(c1.CODE_NOM_MERE_REP_LEGAL) IS NOT NULL
)
SELECT
    MATRICULE_CLIENT AS CLIENT,
    TYPE_LIEN AS TYPE_DE_LIEN,
    PERSONNE_SOCIETE_LIEE,
    CLIENT AS NOM_CLIENT,
    RAISON_SOCIALE_LIEE AS PERSONNE_SOCIETE_LIEE_NOM,
    NIVEAU_RISQUE,
    STATUT,
    VALEUR_COMMUNE
FROM ALERTES
WHERE VALEUR_COMMUNE <> 'N/A'
  AND VALEUR_COMMUNE <> 'NA'
  AND VALEUR_COMMUNE <> 'n/a'
  AND VALEUR_COMMUNE <> 'CNI'
  AND VALEUR_COMMUNE <> '9999'
ORDER BY
    ORDRE_RISQUE,
    TYPE_LIEN,
    MATRICULE_CLIENT,
    PERSONNE_SOCIETE_LIEE
