-- Pas de table {CC}_* dédiée pour l'instant.
SELECT
    CAST(NULL AS VARCHAR2(50)) AS CLIENT,
    CAST(NULL AS VARCHAR2(100)) AS TYPE_DE_LIEN,
    CAST(NULL AS VARCHAR2(50)) AS PERSONNE_SOCIETE_LIEE,
    CAST(NULL AS VARCHAR2(200)) AS NOM_CLIENT,
    CAST(NULL AS VARCHAR2(200)) AS PERSONNE_SOCIETE_LIEE_NOM,
    CAST(NULL AS VARCHAR2(20)) AS NIVEAU_RISQUE,
    CAST(NULL AS VARCHAR2(30)) AS STATUT,
    CAST(NULL AS VARCHAR2(200)) AS VALEUR_COMMUNE
FROM DUAL
WHERE 1 = 0
